# Generated by Django 5.1.1 on 2024-10-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='pic',
            field=models.ImageField(upload_to='uplodes/brand'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('baseprice', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('finalprice', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=10)),
                ('description', models.TextField(default='')),
                ('pic1', models.ImageField(upload_to='uplodes/product')),
                ('pic2', models.ImageField(blank=True, default=None, null=True, upload_to='uplodes/product')),
                ('pic3', models.ImageField(blank=True, default=None, null=True, upload_to='uplodes/product')),
                ('pic4', models.ImageField(blank=True, default=None, null=True, upload_to='uplodes/product')),
                ('Subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subcategory')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.brand')),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.maincategory')),
            ],
        ),
    ]
