# Generated by Django 5.1.1 on 2024-10-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_brand_pic_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Subcategory',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
