# Generated by Django 5.1.2 on 2024-10-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uplodes/users'),
        ),
    ]
