# Generated by Django 5.1.2 on 2024-10-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_buyer_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='pin',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
