# Generated by Django 5.1.2 on 2024-10-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_buyer_phone_alter_buyer_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='phone',
        ),
    ]
